package com.module.notelycompose.notes.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.runtime.Immutable

@Immutable
data class CustomColors(
    // --- Legacy fields (kept for the ~40 existing call sites; re-pointed at Palette.kt) ---
    val sortAscendingIconColor: Color,
    val backgroundViewColor: Color,
    val dateContentColorViewColor: Color,
    val dateContentIconColor: Color,
    val bottomBarBackgroundColor: Color,
    val bottomBarIconColor: Color,
    val noteListBackgroundColor: Color,
    val bodyBackgroundColor: Color,
    val contentTopColor: Color,
    val bodyContentColor: Color,
    val onBodyColor: Color,
    val floatActionButtonBorderColor: Color,
    val floatActionButtonIconColor: Color,
    val searchOutlinedTextFieldColor: Color,
    val topButtonIconColor: Color,
    val noteTextColor: Color,
    val noteIconColor: Color,
    val iOSBackButtonColor: Color,
    val transparentColor: Color,
    val bottomFormattingContainerColor: Color,
    val bottomFormattingContentColor: Color,
    val activeThumbTrackColor: Color,
    val playerBoxBackgroundColor: Color,
    val starredColor: Color,
    val settingsIconColor: Color,
    val settingCancelBackgroundColor: Color,
    val settingCancelTextColor: Color,
    val settingLanguageBackgroundColor: Color,
    val languageSearchBorderColor: Color,
    val languageSearchCancelButtonColor: Color,
    val languageSearchCancelIconTintColor: Color,
    val languageListHeaderColor: Color,
    val languageListTextColor: Color,
    val languageListBackgroundColor: Color,
    val languageListDividerColor: Color,
    val languageSearchUnfocusedColor: Color,
    val shareDialogBackgroundColor: Color,
    val shareDialogButtonColor: Color,
    val statusBarBackgroundColor: Color,
    val settingsBodyTextColor: Color,
    val settingsBodyBorderColor: Color,
    val selectAllCheckboxColor: Color,
    val selectAllCancelColor: Color,
    val modelSelectionDescColor: Color,
    val modelSelectionBgColor: Color,

    // --- New semantic roles for the purple design system (Sep 2026 redesign) ---
    val surface: Color,
    val surfaceElevated: Color,
    val surfaceSunken: Color,
    val onSurface: Color,
    val onSurfaceVariant: Color,
    val outline: Color,
    val accent: Color,
    val onAccent: Color,
    val accentSoft: Color,
    val chipSelectedBg: Color,
    val chipSelectedFg: Color,
    val chipUnselectedBg: Color,
    val chipUnselectedFg: Color,
    val heroGradientStart: Color,
    val heroGradientEnd: Color,
    val danger: Color,
    val onDanger: Color,
    val dangerSoft: Color,
    val success: Color,
    val shadowTint: Color
)
